server.port=8080

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://YOUR_REMOTE_HOST_URL:PORT/nexus_wms?useSSL=false&serverTimezone=UTC
spring.datasource.username=YOUR_REMOTE_USERNAME
spring.datasource.password=YOUR_REMOTE_PASSWORD

# JPA & Hibernate Configuration for MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect